#ifndef DADOS_H_INCLUDED
#define DADOS_H_INCLUDED

 void TiraDadoInicial(int &CantidadJugadores, int ValorDadoInicial[],
                      int NombreJugadorNumero[], std::string NombreJugadorLetras[],
                      int &ValorInicialMaximo); ///[11].-
void DibujarDado(int Valor); ///[14].-
void TirarDadosObjetivo (int CantidadDadosObjetivo, int DadoObjetivo[],
                          int NumeroObjetivo); ///[15].-
void CeroNumeroObjetivo(int NumeroObjetivo); ///[16].-





#endif // DADOS_H_INCLUDED
